credentials:
  usernames:
    victor:
      email: victor@aberration.com
      name: victor
      password: $2b$12$.ejUPQtRJR9cLgZd.e7fUeBpUFf5gXT/9RwXsZNCKhvWuT96wsywK
    femi:
      email: fdeala30@gmail.com
      name: femi
      password: $2b$12$Kawwh/6JHATHhQLSZ0wscuv7jVosi6hCfkn2Q9AaJzeXmJ6KGmXSO
cookie:
  expiry_days: 30
  key: overnight_signature_key # Must be string
  name: overnight_cookie_name
preauthorized:
  emails:
