credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$V2Vo5pFTrUUSQZXLeXI1y.JT4F0OJC2/XOLkwbrPtuVTx8/7WwJiW
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$ie.epLr9fxvRH2K/jdoYIOn6s8SyaAUKQK8AZuPHk1BGFs8Ta.7XW
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
