credentials:
  usernames:
    victor:
      email: victor@aberration.com
      name: victor
      password: $2b$12$.ejUPQtRJR9cLgZd.e7fUeBpUFf5gXT/9RwXsZNCKhvWuT96wsywK
    femi:
      email: fdeala30@gmail.com
      name: femi
      password: $2b$12$UvE1MgvDaNSWihgnHD6mJOxSTmfS8hVP8075X2Qb6rQlMwqHLC3QC
cookie:
  expiry_days: 30
  key: overnight_signature_key # Must be string
  name: overnight_cookie_name
preauthorized:
  emails:
