credentials:
  usernames:
    victor:
      email: victor@aberration.com
      name: victor
      password: $2b$12$.ejUPQtRJR9cLgZd.e7fUeBpUFf5gXT/9RwXsZNCKhvWuT96wsywK
    femi:
      email: fdeala30@gmail.com
      name: femi
      password: $2b$12$8oUrYQqJ9XH8qogfTaukAukSUJnOpQAebmhPhKg1d5FsKiqiFoBWO
cookie:
  expiry_days: 30
  key: move-ai_signature_key # Must be string
  name: move-ai_cookie_name
preauthorized:
  emails:
