# Everything in this section will be available as an environment variable 
VECTOR_STORE_ID = "vs_6858ab8cb9e881919572b5b2f09669df"
MATH_ASSISTANT_ID = "asst_CE2FhokCAd4uD9uQhybDGFoX"
MATH_ASSISTANT2_ID = "asst_2HAOmooNuVwzzBlN3Kg39e5W"
